# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win_set_import_folder.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_modal_win_choose_import_folder(object):
    def setupUi(self, modal_win_choose_import_folder):
        modal_win_choose_import_folder.setObjectName("modal_win_choose_import_folder")
        modal_win_choose_import_folder.resize(400, 180)
        modal_win_choose_import_folder.setMinimumSize(QtCore.QSize(400, 180))
        modal_win_choose_import_folder.setMaximumSize(QtCore.QSize(400, 180))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pics/gui_res/ico_ser.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        modal_win_choose_import_folder.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(modal_win_choose_import_folder)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(modal_win_choose_import_folder)
        self.label_2.setMaximumSize(QtCore.QSize(75, 75))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/pics/gui_res/ico_albert.ico"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(modal_win_choose_import_folder)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_set_import_folder = QtWidgets.QPushButton(modal_win_choose_import_folder)
        self.btn_set_import_folder.setObjectName("btn_set_import_folder")
        self.horizontalLayout.addWidget(self.btn_set_import_folder)
        self.btn_cancel_import_folder_choose = QtWidgets.QPushButton(modal_win_choose_import_folder)
        self.btn_cancel_import_folder_choose.setObjectName("btn_cancel_import_folder_choose")
        self.horizontalLayout.addWidget(self.btn_cancel_import_folder_choose)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(modal_win_choose_import_folder)
        QtCore.QMetaObject.connectSlotsByName(modal_win_choose_import_folder)

    def retranslateUi(self, modal_win_choose_import_folder):
        _translate = QtCore.QCoreApplication.translate
        modal_win_choose_import_folder.setWindowTitle(_translate("modal_win_choose_import_folder", "Обрати типову папку імпорту таблиць"))
        self.label.setText(_translate("modal_win_choose_import_folder", "Типова папка імпорту ще не обиралась. З типової папки будуть завантажуватись усі файли, які можуть бути опрацьовані (.xls, .xlsx, .xml, .txt, .csv, .dec). Додавання буде відбуватись при натисканні на кнопку \"Папка імпорту\", при цьому вже додані файли не будуть видалені. Також проводиться перевірка на повторне завантаження файлів. \n"
"\n"
"Обрати розташування типової папки на комп\'ютері? "))
        self.btn_set_import_folder.setText(_translate("modal_win_choose_import_folder", "Обрати"))
        self.btn_cancel_import_folder_choose.setText(_translate("modal_win_choose_import_folder", "Скасувати"))
import gui.res_file_rc
